#! /bin/bash
#
# This is a shell script DWI preprocessing
#
# Dependencies: (1)FSL (2)MRtrix3
#
# Creator: Kwok-Shing Chan @ MGH
# kchan2@mgh.harvard.edu
#
# Date created: 26 April 2024
# Date edit:
############################################################

# Old Anaconda environment
# # create symlink for weight directory
# TRACTSEG_WEIGHTS_DIR=/autofs/space/symphony_002/users/kwokshing/anaconda3/envs/tractseg_env/lib/python3.11/site-packages/tractseg/weights/
# tractseg_HOME=~/.tractseg
# if [ ! -f "${tractseg_HOME}/pretrained_weights_endings_segmentation_v4.npz" ]; then
#     if [ -d "${tractseg_HOME}" ]; then
#         rm -r ${tractseg_HOME}  # remove existing directory
#     fi
#     ln -s ${TRACTSEG_WEIGHTS_DIR} ${tractseg_HOME}  # create symlink
# fi

# ##### MRtrix3 PATH automatically generated by set_path script - do NOT modify:
# export PATH="/autofs/cluster/pubsw/2/pubsw/Linux2-2.3-x86_64/packages/mrtrix/3.0.3/bin:$PATH"

# # Change the value for FSLDIR if you have
# # installed FSL into a different location
# FSLDIR=/usr/pubsw/packages/fsl/6.0.7.3
# . ${FSLDIR}/etc/fslconf/fsl.sh
# PATH=${FSLDIR}/bin:${PATH}
# export FSLDIR PATH

# # source anadonda base
# source /autofs/space/linen_001/users/kwokshing/tools/bidscoin_4mgh/initiate_conda.sh 

# # activate virtual environment
# source activate tractseg_env

# echo "To completely deactivate the conda environment, use 'conda deactivate' 2 times"

# Miniforge3 envionment
# create symlink for weight directory
TRACTSEG_WEIGHTS_DIR=//autofs/space/symphony_002/users/kwokshing/miniforge3/envs/tractseg_env/lib/python3.9/site-packages/tractseg/weights/
tractseg_HOME=~/.tractseg
if [ ! -f "${tractseg_HOME}/pretrained_weights_endings_segmentation_v4.npz" ]; then
    if [ -d "${tractseg_HOME}" ]; then
        rm -r ${tractseg_HOME}  # remove existing directory
    fi
    ln -s ${TRACTSEG_WEIGHTS_DIR} ${tractseg_HOME}  # create symlink
fi

##### MRtrix3 PATH automatically generated by set_path script - do NOT modify:
export PATH="/autofs/cluster/pubsw/2/pubsw/Linux2-2.3-x86_64/packages/mrtrix/3.0.3/bin:$PATH"

# Change the value for FSLDIR if you have
# installed FSL into a different location
FSLDIR=/usr/pubsw/packages/fsl/6.0.7.3
. ${FSLDIR}/etc/fslconf/fsl.sh
PATH=${FSLDIR}/bin:${PATH}
export FSLDIR PATH

# source miniforge base
source /autofs/space/linen_001/users/kwokshing/tools/bidscoin_4mgh/initiate_conda.sh 

# activate virtual environment
source activate tractseg_env

echo "To completely deactivate the conda environment, use 'conda deactivate' 2 times"

